name: flutter_tips
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Icon adn Themes
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.4
  flex_color_scheme: ^7.0.5

  # State
  flutter_hooks: ^0.18.5+1
  hooks_riverpod: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
